---

- name: create sonarqube pr trigger user
  user: name=checkpr home={{sonar_checkpr_home}}

- name: create sonarqube pr trigger script directory
  file: path=/usr/local/checkpr owner=checkpr mode="u=rwx,go=" state=directory

- name: install sonarqube pr trigger script
  template: src=checkpr.sh.j2 dest=/usr/local/checkpr/checkpr.sh owner=checkpr mode="u=rwx,go="

- name: install .githubrc
  template: src=githubrc.j2 dest={{sonar_checkpr_home}}/.githubrc owner=checkpr

- name: adding checkpr to cron
  cron:
    name=checkpr
    user=checkpr
    job=/usr/local/checkpr/checkpr.sh
    minute=*/15
